import React from 'react'

const NewsPage = () => {
	return (
		<div>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
			<h3>THIS PAGE DOES NOT EXIST. PLEASE TAP HERE</h3>
		</div>
	)
}

export default NewsPage
